/**
 * Redux action type constants (Appdev-style).
 * CasaClick uses RTK thunks in reducers/auth.ts — these names match the reference repo pattern.
 */

// Auth
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

export const USER_GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

export const REFRESH_PROFILE = 'REFRESH_PROFILE';
export const REFRESH_PROFILE_COMPLETED = 'REFRESH_PROFILE_COMPLETED';

// Properties (Appdev: products)
export const GET_LISTINGS = 'GET_LISTINGS';
export const GET_LISTINGS_REQUEST = 'GET_LISTINGS_REQUEST';
export const GET_LISTINGS_COMPLETED = 'GET_LISTINGS_COMPLETED';
export const GET_LISTINGS_ERROR = 'GET_LISTINGS_ERROR';

// Bookings / lease applications (Appdev: orders)
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATIONS_REQUEST = 'GET_APPLICATIONS_REQUEST';
export const GET_APPLICATIONS_COMPLETED = 'GET_APPLICATIONS_COMPLETED';
export const GET_APPLICATIONS_ERROR = 'GET_APPLICATIONS_ERROR';
export const CREATE_APPLICATION_REQUEST = 'CREATE_APPLICATION_REQUEST';
export const CREATE_APPLICATION_COMPLETED = 'CREATE_APPLICATION_COMPLETED';
export const CREATE_APPLICATION_ERROR = 'CREATE_APPLICATION_ERROR';

// Payments
export const GET_PAYMENTS_REQUEST = 'GET_PAYMENTS_REQUEST';
export const GET_PAYMENTS_COMPLETED = 'GET_PAYMENTS_COMPLETED';
export const GET_PAYMENTS_ERROR = 'GET_PAYMENTS_ERROR';
